image: barckcode/bc-app:1.0

stages:
 - build
 - test

build_job:
  stage: build
  script:
   - python3 -V
   - pip3 -V


test_job:
  image: barckcode/pytest:1.0
  stage: test
  script:
   - pytest -v
