image: barckcode/bc-app:1.0

stages:
 - build
 - test
 - deploy

build_job:
  stage: build
  script:
   - python3 -V
   - pip3 -V
   - pytest -V


test_job:
  stage: test
  script:
   - pytest -v


deploy_job:
  stage: deploy
  image: barckcode/bc-app:1.0
  script:
   - python3 main.py
