default:
  image: ubuntu:20.10
  before_script:
   - apt-get update
   - apt-get install -y --no-install-recommends python3 python3-pip
   - pip3 install -r requirements.txt
   - pip3 install pymongo[srv]

  script:
   - python3 main.py
