version: "3.8"

services:
  bot_app_test:
    container_name: bot_test
    build:
      context: .
      dockerfile: Dockerfile-test
    env_file: .env
    volumes:
      - ".:/test/:rw"
  bot_app:
    container_name: bot_development
    build:
      context: .
      dockerfile: Dockerfile
    dns: 8.8.8.8
    env_file: .env
    volumes:
     - ".:/apps/:rw"
  bot_app_prod:
    container_name: bot_prod
    build:
     context: .
     dockerfile: Dockerfile-prod
    env_file: .env
