version: "3.8"

services:
  bot_app_test:
    container_name: bot_app_test
    build:
      context: .
      dockerfile: Dockerfile-test
    env_file: .env
    volumes:
      - ".:/test/:rw"
  bot_app:
    container_name: bot_app
    build:
      context: .
      dockerfile: Dockerfile
    dns: 8.8.8.8
    env_file: .env
    volumes:
     - ".:/apps/:rw"
